vim.keymap.set("n", "<leader>}}", "ysiw}", {remap = true})
vim.keymap.set("n", "<leader>{{", "ysiw{", {remap = true})
vim.keymap.set("n", "<leader>))", "ysiw)", {remap = true})
vim.keymap.set("n", "<leader>((", "ysiw(", {remap = true})
vim.keymap.set("n", '<leader>""', 'ysiw"', {remap = true})
vim.keymap.set("n", "<leader>''", "ysiw'", {remap = true})
