require("config.options")
require("config.mappings")
require("config.lsp.cmp")
require("config.lsp.diagnostic")
require("config.lsp.lspconfig")

require("plugins.aerial")
require("plugins.colorscheme")
require("plugins.fzf")
require("plugins.harpoon")
require("plugins.inc-rename")
require("plugins.lsp_signature")
require("plugins.mason")
require("plugins.neo-tree")
require("plugins.nvim-autopairs")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.vim-surround")

require("autocommands.filetype")

require("functions")
