require("config.options")
require("config.mappings")
require("config.lsp-cmp")
require("config.lsp-diagnostic")
require("config.lsp-config")

require("plugins.aerial")
require("plugins.colorscheme")
require("plugins.fzf")
require("plugins.lsp_signature")
require("plugins.mason")
require("plugins.neo-tree")
require("plugins.nvim-autopairs")
require("plugins.nvim-dap")
require("plugins.taboo")
require("plugins.telescope")
require("plugins.treesitter")
require("plugins.vim-surround")

require("autocommands.filetype")

require("functions")
