# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
if [ -d ~/.dotfiles/bash/config ]; then
	for rc in ~/.dotfiles/bash/config/*; do
		[ -f "$rc" ] && source "$rc"
	done
fi
unset rc

# load fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# determine search program for fzf
if type fd &> /dev/null; then
	export FZF_DEFAULT_COMMAND='fd --type file --hidden --follow --no-ignore-vcs'
	export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# load virtualenvwrapper
[ -f ~/.local/bin/virtualenvwrapper.sh ] && source ~/.local/bin/virtualenvwrapper.sh

# terminal prompt
# export PS1=" \[\e[00;33m\]\w \[\e[0m\] \$ "
build_ps1() {
    local prompt_color='\[\e[33m\]'
    local host=''
    [[ $UID -eq 0 ]] && prompt_color='\[\e[1;31m\]'
    [[ $SSH_TTY ]] && host="@$HOSTNAME "
    echo "${prompt_color}${host}\w\[\e[0m\] \$ "
}
PS1=$(build_ps1)
